version: 2
updates:
  - package-ecosystem: github-actions
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: /
    schedule:
      interval: weekly
      day: sunday
      time: "10:00"
    groups:
      all-actions:
        patterns: [ "*" ]
    commit-message:
      prefix: "chore(deps):"
    labels:
      - "dependencies"
      - "github actions"