export { Template as basic } from "./basic"
export { Template as hero } from "./hero"
export { Template as imageRight } from "./image-right"
export { Template as logos } from "./logos"
export { Template as notice } from "./notice"
export { Template as appScreenshot } from "./app-screenshot"
