name: Release

on:
  push:
    branches:
      - main

jobs:
  check-tools:
    uses: ./.github/workflows/check-tools.ci.yml
    secrets: inherit

  release:
    runs-on: ubuntu-latest
    needs: check-tools
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # nécessaire pour push
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - run: yarn install --frozen-lockfile
      - name: Bump version
        run: |
          yarn version --patch --no-git-tag-version
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add package.json
          git commit -m "chore: bump version [skip ci]"
          git push origin HEAD:master
      - run: yarn build
      - name: Zip build
        run: |
          VERSION=$(node -p "require('./package.json').version")
          zip -r build-$VERSION.zip .next public package.json yarn.lock
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: build-*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
